FROM golang:1.25-alpine AS builder
WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o postnest-worker ./cmd/worker

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=builder /build/postnest-worker /usr/local/bin/postnest-worker
ENTRYPOINT ["/usr/local/bin/postnest-worker"]
