FROM golang:1.25-alpine AS builder
WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o postnest-server ./cmd/server

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=builder /build/postnest-server /usr/local/bin/postnest-server
EXPOSE 8080 143 587 993 465
ENTRYPOINT ["/usr/local/bin/postnest-server"]
